default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miller_development
  host: localhost
  username: pguser
  password: 1024

test:
  <<: *default
  database: miller_test
  host: localhost
  username: pguser
  password: 1024

production:
  <<: *default
  database: miller_production
  username: online_school
  password: <%= ENV['ONLINE_SCHOOL_DATABASE_PASSWORD'] %>
